export {default as Hero} from './Hero.jsx'
export {default as About} from './About.jsx'
export {default as FeaturedRecipes} from './FeaturedRecipes.jsx'
export {default as Users} from './Users.jsx'
export {default as Blog} from './Blog.jsx'
export {default as CTA} from './CTA.jsx'
export {default as Footer} from './Footer.jsx'